# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/athena/projects/github/AthenaProject/Python/CamerPositionCalibration/CalibrationP1.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(628, 460)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.pushButtonGotoP1 = QtWidgets.QPushButton(Frame)
        self.pushButtonGotoP1.setObjectName("pushButtonGotoP1")
        self.verticalLayout_2.addWidget(self.pushButtonGotoP1)
        self.buttonP = QtWidgets.QPushButton(Frame)
        self.buttonP.setObjectName("buttonP")
        self.verticalLayout_2.addWidget(self.buttonP)
        self.buttonPP = QtWidgets.QPushButton(Frame)
        self.buttonPP.setObjectName("buttonPP")
        self.verticalLayout_2.addWidget(self.buttonPP)
        self.ButtonNN = QtWidgets.QPushButton(Frame)
        self.ButtonNN.setObjectName("ButtonNN")
        self.verticalLayout_2.addWidget(self.ButtonNN)
        self.buttonN = QtWidgets.QPushButton(Frame)
        self.buttonN.setObjectName("buttonN")
        self.verticalLayout_2.addWidget(self.buttonN)
        self.labelValue = QtWidgets.QLabel(Frame)
        self.labelValue.setObjectName("labelValue")
        self.verticalLayout_2.addWidget(self.labelValue)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.pushButtonTest = QtWidgets.QPushButton(Frame)
        self.pushButtonTest.setObjectName("pushButtonTest")
        self.verticalLayout_2.addWidget(self.pushButtonTest)
        self.pushButtonExit = QtWidgets.QPushButton(Frame)
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.verticalLayout_2.addWidget(self.pushButtonExit)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_image_1 = QtWidgets.QLabel(Frame)
        self.label_image_1.setObjectName("label_image_1")
        self.verticalLayout.addWidget(self.label_image_1)
        self.label_image_2 = QtWidgets.QLabel(Frame)
        self.label_image_2.setObjectName("label_image_2")
        self.verticalLayout.addWidget(self.label_image_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 9)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "Calibrate P1"))
        self.pushButtonGotoP1.setText(_translate("Frame", "Go To P1"))
        self.buttonP.setText(_translate("Frame", "+ 0.1mm"))
        self.buttonPP.setText(_translate("Frame", "+ 1mm"))
        self.ButtonNN.setText(_translate("Frame", "- 1mm"))
        self.buttonN.setText(_translate("Frame", "- 0.1mm"))
        self.labelValue.setText(_translate("Frame", "Current:"))
        self.pushButtonTest.setText(_translate("Frame", "Test"))
        self.pushButtonExit.setText(_translate("Frame", "Done"))
        self.label_image_1.setText(_translate("Frame", "TextLabel"))
        self.label_image_2.setText(_translate("Frame", "TextLabel"))
